const STORAGE='bot-shop-real-assets-v1';
const bots=[
{id:'mara',name:'Mara',tag:'The Investigator',bio:'Patient, observant and suspicious of things that seem slightly wrong.',prefs:{mysterious:10,old:7,domestic:4,colorful:3,broken:8,sentimental:5}},
{id:'otto',name:'Otto',tag:'The Sentimentalist',bio:'Forms emotional attachments to ordinary objects very quickly.',prefs:{mysterious:4,old:9,domestic:8,colorful:5,broken:7,sentimental:10}},
{id:'june',name:'June',tag:'The Skeptic',bio:'Does not understand why everyone keeps bringing useless things home.',prefs:{mysterious:1,old:3,domestic:9,colorful:2,broken:1,sentimental:2}},
{id:'felix',name:'Felix',tag:'The Cataloguer',bio:'Likes patterns, categories and repeated objects.',prefs:{mysterious:6,old:6,domestic:5,colorful:4,broken:3,sentimental:4}},
{id:'dot',name:'Dot',tag:'The Minimalist',bio:'Rarely keeps anything. When Dot chooses something, it usually matters.',prefs:{mysterious:4,old:3,domestic:2,colorful:3,broken:2,sentimental:7}},
{id:'arthur',name:'Arthur',tag:'The Nostalgist',bio:'Feels nostalgia for places and decades he never experienced.',prefs:{mysterious:5,old:10,domestic:7,colorful:3,broken:5,sentimental:9}},
{id:'nell',name:'Nell',tag:'The Contrarian',bio:'Becomes interested in objects other residents seem to ignore.',prefs:{mysterious:9,old:4,domestic:3,colorful:5,broken:9,sentimental:4}},
{id:'milo',name:'Milo',tag:'The Observer',bio:'Pays close attention to what everyone else chooses.',prefs:{mysterious:5,old:5,domestic:5,colorful:5,broken:5,sentimental:5}},
{id:'iris',name:'Iris',tag:'The Aesthete',bio:'Responds strongly to color, composition and visual oddity.',prefs:{mysterious:4,old:4,domestic:3,colorful:10,broken:3,sentimental:5}},
{id:'gus',name:'Gus',tag:'The Unknown',bio:'Has no particularly strong tastes yet.',prefs:{mysterious:5,old:5,domestic:5,colorful:5,broken:5,sentimental:5}}];
const spots=[{n:'north shelves',x:29,y:22,c:'old'},{n:'oddities',x:44,y:31,c:'mysterious'},{n:'green display',x:34,y:51,c:'sentimental'},{n:'red display',x:70,y:51,c:'mysterious'},{n:'counter',x:16,y:80,c:'domestic'},{n:'couch',x:80,y:78,c:'sentimental'},{n:'south aisle',x:55,y:80,c:'old'}];
const itemDefs=[
['clock','Clock','old'],['radio','Radio','old'],['camera','Camera','old'],['telephone','Telephone','old'],['typewriter','Typewriter','old'],['globe','Globe','colorful'],['book','Book','sentimental'],['mug','Mug','domestic'],['vase','Vase','domestic'],['bottle','Bottle','mysterious'],['lantern','Lantern','old'],['jar_red','Red Jar','mysterious'],['key','Key','mysterious'],['coin','Coin','old'],['painting','Painting','colorful'],['statue','Statue','old'],['hourglass','Hourglass','old'],['gramophone','Gramophone','old'],['candle','Candle','domestic'],['plant_small','Potted Plant','domestic'],['figurine','Figurine','sentimental'],['mask','Mask','mysterious'],['skull','Skull','mysterious'],['telescope','Telescope','old'],['box','Decorated Box','mysterious'],['jar_blue','Blue Jar','mysterious'],['duck','Rubber Duck','colorful']];
const adjectives=['Faded','Blue','Red','Green','Old','Dusty','Tiny','Heavy','Painted','Chipped','Quiet','Brass','Cream','Strange'];
const ordinary=['It shows signs of ordinary use.','The label is partially faded.','One edge is carefully repaired.','There is a small scratch on the underside.','It looks as though someone kept it for years.'];
const odd=['The maker’s mark has been removed.','A tiny number is written underneath.','One part does not quite match the rest.','There is a compartment with no obvious purpose.','The serial number is unusually short.'];
const strange=['The instructions mention a button that does not exist.','A date on the underside has not happened yet.','Its underside reads SECOND ATTEMPT.','A handwritten note says PLEASE RETURN BEFORE THURSDAY.','A symbol appears twice, but only from one angle.'];
let world=load();
function fresh(){const w={collections:{},inventory:[],activity:[],positions:{},nextId:1};bots.forEach((b,i)=>{w.collections[b.id]=[];w.positions[b.id]={x:20+(i%5)*14,y:38+Math.floor(i/5)*25}});for(let i=0;i<24;i++)w.inventory.push(makeItem(w));w.activity.unshift({t:Date.now(),text:'The shop opened.'});return w}
function makeItem(w=world){const d=itemDefs[Math.floor(Math.random()*itemDefs.length)];const roll=Math.random();const p=roll<.6?ri(1,30):roll<.9?ri(31,65):ri(66,100);const pool=p<31?ordinary:p<66?[...ordinary,...odd]:[...odd,...strange];return{id:w.nextId++,key:d[0],base:d[1],name:`${random(adjectives)} ${d[1]}`,category:d[2],peculiarity:p,description:random(pool)}}
function score(bot,o){let v=Math.random()*5+(bot.prefs[o.category]||0);if(o.peculiarity>60)v+=(bot.prefs.mysterious||0)*.35;if(o.peculiarity>85)v+=2;if(bot.id==='dot')v-=5;if(bot.id==='felix')v+=world.collections[bot.id].filter(x=>x.category===o.category).length*1.7;if(bot.id==='milo')v+=Object.values(world.collections).flat().filter(x=>x.category===o.category).length*.25;return v}
function reason(bot,o){const r={mara:['Something about this feels unresolved.','I want to inspect this again later.'],otto:['Someone kept this for a reason.','I could not leave it behind.'],june:['At least this one seems useful.','This is less pointless than most of the others.'],felix:['This fits with the others.','I am beginning to notice a pattern.'],dot:['I kept coming back to this one.','Most things here are noise. This is not.'],arthur:['I feel like I have seen this before.','It reminds me of somewhere I have never been.'],nell:['Nobody else seemed interested.','Everyone walked past this.'],milo:['I have noticed others choosing things like this.','There seems to be something here.'],iris:['It would look right on the shelf.','The color convinced me.'],gus:['I do not know. I just chose it.','Maybe this is the beginning of something.']};return random(r[bot.id])}
async function visit(bot){const spot=random(spots);move(bot,spot.x,spot.y);add(`${bot.name} moved to ${spot.n}.`);await sleep(1500);const cand=world.inventory.filter(o=>o.category===spot.c||Math.random()<.28).sort(()=>Math.random()-.5).slice(0,4);if(!cand.length)return;let best=null,bs=-99;cand.forEach(o=>{const s=score(bot,o);if(s>bs){bs=s;best=o}});think(bot,'question');add(`${bot.name} is inspecting ${best.name}.`);await sleep(1500);think(bot,null);const th=bot.id==='dot'?12:8;if(bs>th&&Math.random()>.34){world.inventory=world.inventory.filter(o=>o.id!==best.id);const owned={...best,reason:reason(bot,best),acquired:Date.now()};world.collections[bot.id].push(owned);think(bot,'heart');add(`${bot.name} picked up ${best.name}.`);await sleep(1200);think(bot,null);world.inventory.push(makeItem())}save();render()}
function botEl(bot){let el=document.getElementById('bot-'+bot.id);if(el)return el;el=document.createElement('div');el.className='bot';el.id='bot-'+bot.id;el.innerHTML=`<img class="sprite" src="assets/bots/${bot.id}_down_1.png?v=native"><img class="bubble" src="assets/ui/thought_question.png?v=native"><div class="name">${bot.name}</div>`;document.getElementById('botLayer').appendChild(el);return el}
function move(bot,x,y){const el=botEl(bot);el.style.left=x+'%';el.style.top=y+'%';world.positions[bot.id]={x,y};let f=1,steps=0;const timer=setInterval(()=>{f=f%3+1;el.querySelector('.sprite').src=`assets/bots/${bot.id}_down_${f}.png?v=native`;if(++steps>8){clearInterval(timer);el.querySelector('.sprite').src=`assets/bots/${bot.id}_down_1.png?v=native`}},140);save()}
function think(bot,type){const el=botEl(bot),b=el.querySelector('.bubble');if(!type){el.classList.remove('thinking');return}b.src=`assets/ui/thought_${type}.png?v=native`;el.classList.add('thinking')}
function add(text){world.activity.unshift({t:Date.now(),text});world.activity=world.activity.slice(0,120);renderActivity();save()}
function renderBots(){const list=document.getElementById('botList');list.innerHTML='';bots.forEach(b=>{const pos=world.positions[b.id];const el=botEl(b);el.style.left=pos.x+'%';el.style.top=pos.y+'%';const row=document.createElement('div');row.className='botRow';row.innerHTML=`<img class="portrait" src="assets/bots/${b.id}_down_1.png?v=native"><div><div class="botName">${b.name}</div><div class="botTag">${b.tag}</div></div><div class="count">Items: ${world.collections[b.id].length}</div>`;row.onclick=()=>openProfile(b.id);list.appendChild(row)})}
function renderShop(){document.getElementById('shopList').innerHTML=world.inventory.slice(0,18).map(o=>`<div class="shopItem"><img src="assets/items/${o.key}.png?v=native"><div><strong>${o.name}</strong><div>${o.description}</div></div></div>`).join('')}
function renderActivity(){const m=a=>`<div class="entry">${a.text}</div>`;document.getElementById('miniActivity').innerHTML=world.activity.slice(0,12).map(m).join('');document.getElementById('fullActivity').innerHTML=world.activity.map(m).join('')}
function openProfile(id){const b=bots.find(x=>x.id===id),c=world.collections[id];document.getElementById('modalTitle').textContent=`${b.name} — ${b.tag}`;document.getElementById('modalBio').textContent=b.bio;document.getElementById('collection').innerHTML=c.length?c.map(o=>`<div class="card"><img src="assets/items/${o.key}.png?v=native"><h4>${o.name}</h4><p>${o.description}</p><div class="reason">“${o.reason}”</div></div>`).join(''):'<div class="card"><h4>Nothing collected yet.</h4></div>';document.getElementById('modal').classList.add('open')}
function render(){renderBots();renderShop();renderActivity();save()}
function save(){localStorage.setItem(STORAGE,JSON.stringify(world))}function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE));return x||fresh()}catch{return fresh()}}
function random(a){return a[Math.floor(Math.random()*a.length)]}function ri(a,b){return Math.floor(Math.random()*(b-a+1))+a}function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.getElementById(t.dataset.panel).classList.add('active')});document.getElementById('closeModal').onclick=()=>document.getElementById('modal').classList.remove('open');document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')e.currentTarget.classList.remove('open')};setInterval(()=>document.getElementById('clock').textContent=new Date().toLocaleTimeString(),1000);render();setTimeout(function loop(){visit(random(bots));setTimeout(loop,ri(5500,9000))},1800);